/*
 * AutoGenerateData.h
 *
 *  Created on: 2018年3月28日
 *      Author: yzg
 */

#ifndef AUTOGENERATEDATA_H_
#define AUTOGENERATEDATA_H_

#include "adt_datatype.h"


#define SPRINGUNIT 30
#define PI	       3.141592

typedef struct
{
	FP32 	OD[2];					//上下外径(几何形状)
	FP32    ODv[2];					//对应外径轴的值
	FP32	pitch;					//节距
	FP32	circles;				//圈数
	INT32S	splitCs;				//拆成的单元圈数
}SpringUnit;						//弹簧单元


typedef struct
{
	INT32S  units;					//单元个数
	INT32S  kfAxisNo;				//切刀轴号
	INT32S  odAxisNo;				//外径轴号
	INT32S  ptAxisNo;				//节距轴号
	FP32    stPos;					//节距轴开始的位置
	FP32 	tPos;					//节距刚好触碰钢丝的位置
	FP32 	wireD;					//线径

	FP32    xOffset;				//圈数补偿
	FP32    yOffset;				//外径补偿
	FP32    pOffset;				//节距补偿

	FP32    downPos;				//进刀位置
	FP32    upPos;					//退刀位置

	FP32    tailSend[2];			//收尾送线

	FP32 	ODs[SPRINGUNIT][2];		//弹簧的上下外径
	FP32    ODv[SPRINGUNIT][2];		//对应的外径轴的值
	FP32	pitch[SPRINGUNIT];		//节距
	FP32	circles[SPRINGUNIT];	//圈数
	INT32S	splitCs[SPRINGUNIT];	//拆成的单元圈数

}Spring;							//弹簧结构



int GraphGenData(INT8U type,TSpringCraftParam* SpringParamP);

#endif /* AUTOGENERATEDATA_H_ */
